---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsm-operator
  namespace: nsm
  labels:
    control-plane: nsm-operator
spec:
  selector:
    matchLabels:
      control-plane: nsm-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: nsm-operator
    spec:
      serviceAccountName: nsm-operator
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 300m
            memory: 200Mi
      terminationGracePeriodSeconds: 10