apiVersion: nsm.networkservicemesh.io/v1alpha1
kind: NSM
metadata:
  name: nsm-sample-registry-k8s
  namespace: nsm
spec:
  version: v1.8.0
#  nsmPullPolicy: IfNotPresent
  nsmLogLevel: TRACE
  
  # Forwarding Plane Configs
  forwarders:
    - type: vpp
      image: ghcr.io/networkservicemesh/cmd-forwarder-vpp:v1.8.0

  registry:
    replicaCount: 1
    type: k8s
    image: ghcr.io/networkservicemesh/cmd-registry-k8s:v1.8.0

  webhook:
    image: ghcr.io/networkservicemesh/cmd-admission-webhook-k8s:v1.8.0
